name: Ditto Text Updater
description: Automatically updates Ditto text in a repository that has ditto-cli initiated
inputs:
  ditto-api-key:
    description: "Your Ditto API key. More info: https://developer.dittowords.com/api-reference#creating-an-api-key"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set current date as env variable
      id: datetime
      run: echo "::set-output name=datetime::$(date +'%Y-%m-%dT-%H%M%S')"
      shell: bash
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - run: npm install --global gh-action-stats
      shell: bash
    - run: export NODE_PATH=$(npm root --quiet -g)
      shell: bash
    - name: Collect stats
      run: node ${{ github.action_path }}/stats.js
      shell: bash
    - run: npm install --global @dittowords/cli
      shell: bash
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Ditto pull
      env:
        DITTO_API_KEY: ${{ inputs.ditto-api-key }}
      shell: bash
      run: |
        npx ditto-cli pull
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        commit-message: "ditto: text update ${{ steps.datetime.outputs.datetime }}" 
        title: Ditto text update ${{ steps.datetime.outputs.datetime  }}
        body: Automated change by the Ditto Text Updater action
        branch: ditto-update-${{ steps.datetime.outputs.datetime }}
